// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/ransomeye.proto

package ransomeyepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RansomEyeService_Handshake_FullMethodName          = "/ransomeye.RansomEyeService/Handshake"
	RansomEyeService_SendTelemetry_FullMethodName      = "/ransomeye.RansomEyeService/SendTelemetry"
	RansomEyeService_SendSignal_FullMethodName         = "/ransomeye.RansomEyeService/SendSignal"
	RansomEyeService_SendHeartbeat_FullMethodName      = "/ransomeye.RansomEyeService/SendHeartbeat"
	RansomEyeService_ReceiveActions_FullMethodName     = "/ransomeye.RansomEyeService/ReceiveActions"
	RansomEyeService_ReportActionResult_FullMethodName = "/ransomeye.RansomEyeService/ReportActionResult"
	RansomEyeService_SendFlowStream_FullMethodName     = "/ransomeye.RansomEyeService/SendFlowStream"
	RansomEyeService_SendDPIEvent_FullMethodName       = "/ransomeye.RansomEyeService/SendDPIEvent"
)

// RansomEyeServiceClient is the client API for RansomEyeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RansomEyeServiceClient interface {
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	// Phase 3 (P0): data plane is opaque canonical bytes inside payload; transport metadata only.
	SendTelemetry(ctx context.Context, in *TelemetryEnvelope, opts ...grpc.CallOption) (*TelemetryAck, error)
	// Mishka authoritative signal ingress (PRD-03 / PRD-07 / PRD-08).
	// This RPC introduces a PRD-compliant envelope without reinterpreting legacy UUID-based fields.
	SendSignal(ctx context.Context, in *SignalEnvelope, opts ...grpc.CallOption) (*SignalAck, error)
	SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatAck, error)
	ReceiveActions(ctx context.Context, in *ActionStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ActionCommand], error)
	ReportActionResult(ctx context.Context, in *ActionResult, opts ...grpc.CallOption) (*ActionAck, error)
	SendFlowStream(ctx context.Context, in *FlowBatch, opts ...grpc.CallOption) (*FlowAck, error)
	SendDPIEvent(ctx context.Context, in *DPIDetectionEvent, opts ...grpc.CallOption) (*DPIEventAck, error)
}

type ransomEyeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRansomEyeServiceClient(cc grpc.ClientConnInterface) RansomEyeServiceClient {
	return &ransomEyeServiceClient{cc}
}

func (c *ransomEyeServiceClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, RansomEyeService_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ransomEyeServiceClient) SendTelemetry(ctx context.Context, in *TelemetryEnvelope, opts ...grpc.CallOption) (*TelemetryAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TelemetryAck)
	err := c.cc.Invoke(ctx, RansomEyeService_SendTelemetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ransomEyeServiceClient) SendSignal(ctx context.Context, in *SignalEnvelope, opts ...grpc.CallOption) (*SignalAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalAck)
	err := c.cc.Invoke(ctx, RansomEyeService_SendSignal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ransomEyeServiceClient) SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatAck)
	err := c.cc.Invoke(ctx, RansomEyeService_SendHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ransomEyeServiceClient) ReceiveActions(ctx context.Context, in *ActionStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ActionCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RansomEyeService_ServiceDesc.Streams[0], RansomEyeService_ReceiveActions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ActionStreamRequest, ActionCommand]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RansomEyeService_ReceiveActionsClient = grpc.ServerStreamingClient[ActionCommand]

func (c *ransomEyeServiceClient) ReportActionResult(ctx context.Context, in *ActionResult, opts ...grpc.CallOption) (*ActionAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionAck)
	err := c.cc.Invoke(ctx, RansomEyeService_ReportActionResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ransomEyeServiceClient) SendFlowStream(ctx context.Context, in *FlowBatch, opts ...grpc.CallOption) (*FlowAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlowAck)
	err := c.cc.Invoke(ctx, RansomEyeService_SendFlowStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ransomEyeServiceClient) SendDPIEvent(ctx context.Context, in *DPIDetectionEvent, opts ...grpc.CallOption) (*DPIEventAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DPIEventAck)
	err := c.cc.Invoke(ctx, RansomEyeService_SendDPIEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RansomEyeServiceServer is the server API for RansomEyeService service.
// All implementations must embed UnimplementedRansomEyeServiceServer
// for forward compatibility.
type RansomEyeServiceServer interface {
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	// Phase 3 (P0): data plane is opaque canonical bytes inside payload; transport metadata only.
	SendTelemetry(context.Context, *TelemetryEnvelope) (*TelemetryAck, error)
	// Mishka authoritative signal ingress (PRD-03 / PRD-07 / PRD-08).
	// This RPC introduces a PRD-compliant envelope without reinterpreting legacy UUID-based fields.
	SendSignal(context.Context, *SignalEnvelope) (*SignalAck, error)
	SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatAck, error)
	ReceiveActions(*ActionStreamRequest, grpc.ServerStreamingServer[ActionCommand]) error
	ReportActionResult(context.Context, *ActionResult) (*ActionAck, error)
	SendFlowStream(context.Context, *FlowBatch) (*FlowAck, error)
	SendDPIEvent(context.Context, *DPIDetectionEvent) (*DPIEventAck, error)
	mustEmbedUnimplementedRansomEyeServiceServer()
}

// UnimplementedRansomEyeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRansomEyeServiceServer struct{}

func (UnimplementedRansomEyeServiceServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedRansomEyeServiceServer) SendTelemetry(context.Context, *TelemetryEnvelope) (*TelemetryAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SendTelemetry not implemented")
}
func (UnimplementedRansomEyeServiceServer) SendSignal(context.Context, *SignalEnvelope) (*SignalAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SendSignal not implemented")
}
func (UnimplementedRansomEyeServiceServer) SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedRansomEyeServiceServer) ReceiveActions(*ActionStreamRequest, grpc.ServerStreamingServer[ActionCommand]) error {
	return status.Error(codes.Unimplemented, "method ReceiveActions not implemented")
}
func (UnimplementedRansomEyeServiceServer) ReportActionResult(context.Context, *ActionResult) (*ActionAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportActionResult not implemented")
}
func (UnimplementedRansomEyeServiceServer) SendFlowStream(context.Context, *FlowBatch) (*FlowAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SendFlowStream not implemented")
}
func (UnimplementedRansomEyeServiceServer) SendDPIEvent(context.Context, *DPIDetectionEvent) (*DPIEventAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SendDPIEvent not implemented")
}
func (UnimplementedRansomEyeServiceServer) mustEmbedUnimplementedRansomEyeServiceServer() {}
func (UnimplementedRansomEyeServiceServer) testEmbeddedByValue()                          {}

// UnsafeRansomEyeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RansomEyeServiceServer will
// result in compilation errors.
type UnsafeRansomEyeServiceServer interface {
	mustEmbedUnimplementedRansomEyeServiceServer()
}

func RegisterRansomEyeServiceServer(s grpc.ServiceRegistrar, srv RansomEyeServiceServer) {
	// If the following call panics, it indicates UnimplementedRansomEyeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RansomEyeService_ServiceDesc, srv)
}

func _RansomEyeService_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RansomEyeServiceServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RansomEyeService_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RansomEyeServiceServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RansomEyeService_SendTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelemetryEnvelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RansomEyeServiceServer).SendTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RansomEyeService_SendTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RansomEyeServiceServer).SendTelemetry(ctx, req.(*TelemetryEnvelope))
	}
	return interceptor(ctx, in, info, handler)
}

func _RansomEyeService_SendSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalEnvelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RansomEyeServiceServer).SendSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RansomEyeService_SendSignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RansomEyeServiceServer).SendSignal(ctx, req.(*SignalEnvelope))
	}
	return interceptor(ctx, in, info, handler)
}

func _RansomEyeService_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RansomEyeServiceServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RansomEyeService_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RansomEyeServiceServer).SendHeartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RansomEyeService_ReceiveActions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ActionStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RansomEyeServiceServer).ReceiveActions(m, &grpc.GenericServerStream[ActionStreamRequest, ActionCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RansomEyeService_ReceiveActionsServer = grpc.ServerStreamingServer[ActionCommand]

func _RansomEyeService_ReportActionResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RansomEyeServiceServer).ReportActionResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RansomEyeService_ReportActionResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RansomEyeServiceServer).ReportActionResult(ctx, req.(*ActionResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _RansomEyeService_SendFlowStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlowBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RansomEyeServiceServer).SendFlowStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RansomEyeService_SendFlowStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RansomEyeServiceServer).SendFlowStream(ctx, req.(*FlowBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _RansomEyeService_SendDPIEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPIDetectionEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RansomEyeServiceServer).SendDPIEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RansomEyeService_SendDPIEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RansomEyeServiceServer).SendDPIEvent(ctx, req.(*DPIDetectionEvent))
	}
	return interceptor(ctx, in, info, handler)
}

// RansomEyeService_ServiceDesc is the grpc.ServiceDesc for RansomEyeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RansomEyeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ransomeye.RansomEyeService",
	HandlerType: (*RansomEyeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _RansomEyeService_Handshake_Handler,
		},
		{
			MethodName: "SendTelemetry",
			Handler:    _RansomEyeService_SendTelemetry_Handler,
		},
		{
			MethodName: "SendSignal",
			Handler:    _RansomEyeService_SendSignal_Handler,
		},
		{
			MethodName: "SendHeartbeat",
			Handler:    _RansomEyeService_SendHeartbeat_Handler,
		},
		{
			MethodName: "ReportActionResult",
			Handler:    _RansomEyeService_ReportActionResult_Handler,
		},
		{
			MethodName: "SendFlowStream",
			Handler:    _RansomEyeService_SendFlowStream_Handler,
		},
		{
			MethodName: "SendDPIEvent",
			Handler:    _RansomEyeService_SendDPIEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReceiveActions",
			Handler:       _RansomEyeService_ReceiveActions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/ransomeye.proto",
}

const (
	ProbeService_RegisterProbe_FullMethodName  = "/ransomeye.ProbeService/RegisterProbe"
	ProbeService_ProbeHeartbeat_FullMethodName = "/ransomeye.ProbeService/ProbeHeartbeat"
	ProbeService_PullConfig_FullMethodName     = "/ransomeye.ProbeService/PullConfig"
	ProbeService_ReportFinding_FullMethodName  = "/ransomeye.ProbeService/ReportFinding"
)

// ProbeServiceClient is the client API for ProbeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProbeServiceClient interface {
	RegisterProbe(ctx context.Context, in *ProbeRegistration, opts ...grpc.CallOption) (*ProbeRegistrationAck, error)
	ProbeHeartbeat(ctx context.Context, in *ProbeHeartbeatRequest, opts ...grpc.CallOption) (*ProbeHeartbeatAck, error)
	PullConfig(ctx context.Context, in *PullConfigRequest, opts ...grpc.CallOption) (*ProbeConfig, error)
	ReportFinding(ctx context.Context, in *NetworkInfraFinding, opts ...grpc.CallOption) (*FindingAck, error)
}

type probeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProbeServiceClient(cc grpc.ClientConnInterface) ProbeServiceClient {
	return &probeServiceClient{cc}
}

func (c *probeServiceClient) RegisterProbe(ctx context.Context, in *ProbeRegistration, opts ...grpc.CallOption) (*ProbeRegistrationAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeRegistrationAck)
	err := c.cc.Invoke(ctx, ProbeService_RegisterProbe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *probeServiceClient) ProbeHeartbeat(ctx context.Context, in *ProbeHeartbeatRequest, opts ...grpc.CallOption) (*ProbeHeartbeatAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeHeartbeatAck)
	err := c.cc.Invoke(ctx, ProbeService_ProbeHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *probeServiceClient) PullConfig(ctx context.Context, in *PullConfigRequest, opts ...grpc.CallOption) (*ProbeConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeConfig)
	err := c.cc.Invoke(ctx, ProbeService_PullConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *probeServiceClient) ReportFinding(ctx context.Context, in *NetworkInfraFinding, opts ...grpc.CallOption) (*FindingAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindingAck)
	err := c.cc.Invoke(ctx, ProbeService_ReportFinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProbeServiceServer is the server API for ProbeService service.
// All implementations must embed UnimplementedProbeServiceServer
// for forward compatibility.
type ProbeServiceServer interface {
	RegisterProbe(context.Context, *ProbeRegistration) (*ProbeRegistrationAck, error)
	ProbeHeartbeat(context.Context, *ProbeHeartbeatRequest) (*ProbeHeartbeatAck, error)
	PullConfig(context.Context, *PullConfigRequest) (*ProbeConfig, error)
	ReportFinding(context.Context, *NetworkInfraFinding) (*FindingAck, error)
	mustEmbedUnimplementedProbeServiceServer()
}

// UnimplementedProbeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProbeServiceServer struct{}

func (UnimplementedProbeServiceServer) RegisterProbe(context.Context, *ProbeRegistration) (*ProbeRegistrationAck, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterProbe not implemented")
}
func (UnimplementedProbeServiceServer) ProbeHeartbeat(context.Context, *ProbeHeartbeatRequest) (*ProbeHeartbeatAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ProbeHeartbeat not implemented")
}
func (UnimplementedProbeServiceServer) PullConfig(context.Context, *PullConfigRequest) (*ProbeConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method PullConfig not implemented")
}
func (UnimplementedProbeServiceServer) ReportFinding(context.Context, *NetworkInfraFinding) (*FindingAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportFinding not implemented")
}
func (UnimplementedProbeServiceServer) mustEmbedUnimplementedProbeServiceServer() {}
func (UnimplementedProbeServiceServer) testEmbeddedByValue()                      {}

// UnsafeProbeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProbeServiceServer will
// result in compilation errors.
type UnsafeProbeServiceServer interface {
	mustEmbedUnimplementedProbeServiceServer()
}

func RegisterProbeServiceServer(s grpc.ServiceRegistrar, srv ProbeServiceServer) {
	// If the following call panics, it indicates UnimplementedProbeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProbeService_ServiceDesc, srv)
}

func _ProbeService_RegisterProbe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeRegistration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProbeServiceServer).RegisterProbe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProbeService_RegisterProbe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProbeServiceServer).RegisterProbe(ctx, req.(*ProbeRegistration))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProbeService_ProbeHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProbeServiceServer).ProbeHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProbeService_ProbeHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProbeServiceServer).ProbeHeartbeat(ctx, req.(*ProbeHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProbeService_PullConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProbeServiceServer).PullConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProbeService_PullConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProbeServiceServer).PullConfig(ctx, req.(*PullConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProbeService_ReportFinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkInfraFinding)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProbeServiceServer).ReportFinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProbeService_ReportFinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProbeServiceServer).ReportFinding(ctx, req.(*NetworkInfraFinding))
	}
	return interceptor(ctx, in, info, handler)
}

// ProbeService_ServiceDesc is the grpc.ServiceDesc for ProbeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProbeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ransomeye.ProbeService",
	HandlerType: (*ProbeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterProbe",
			Handler:    _ProbeService_RegisterProbe_Handler,
		},
		{
			MethodName: "ProbeHeartbeat",
			Handler:    _ProbeService_ProbeHeartbeat_Handler,
		},
		{
			MethodName: "PullConfig",
			Handler:    _ProbeService_PullConfig_Handler,
		},
		{
			MethodName: "ReportFinding",
			Handler:    _ProbeService_ReportFinding_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ransomeye.proto",
}
