// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sine.proto

package sinepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SineRequest) Reset() {
	*x = SineRequest{}
	mi := &file_sine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SineRequest) ProtoMessage() {}

func (x *SineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SineRequest.ProtoReflect.Descriptor instead.
func (*SineRequest) Descriptor() ([]byte, []int) {
	return file_sine_proto_rawDescGZIP(), []int{0}
}

func (x *SineRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reasoning     string                 `protobuf:"bytes,2,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SineResponse) Reset() {
	*x = SineResponse{}
	mi := &file_sine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SineResponse) ProtoMessage() {}

func (x *SineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SineResponse.ProtoReflect.Descriptor instead.
func (*SineResponse) Descriptor() ([]byte, []int) {
	return file_sine_proto_rawDescGZIP(), []int{1}
}

func (x *SineResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *SineResponse) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

var File_sine_proto protoreflect.FileDescriptor

const file_sine_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"sine.proto\x12\x04sine\"'\n" +
	"\vSineRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"F\n" +
	"\fSineResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x1c\n" +
	"\treasoning\x18\x02 \x01(\tR\treasoning2=\n" +
	"\n" +
	"SineEngine\x12/\n" +
	"\x06Filter\x12\x11.sine.SineRequest\x1a\x12.sine.SineResponseB\x1dZ\x1bransomeye/proto/sine;sinepbb\x06proto3"

var (
	file_sine_proto_rawDescOnce sync.Once
	file_sine_proto_rawDescData []byte
)

func file_sine_proto_rawDescGZIP() []byte {
	file_sine_proto_rawDescOnce.Do(func() {
		file_sine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sine_proto_rawDesc), len(file_sine_proto_rawDesc)))
	})
	return file_sine_proto_rawDescData
}

var file_sine_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sine_proto_goTypes = []any{
	(*SineRequest)(nil),  // 0: sine.SineRequest
	(*SineResponse)(nil), // 1: sine.SineResponse
}
var file_sine_proto_depIdxs = []int32{
	0, // 0: sine.SineEngine.Filter:input_type -> sine.SineRequest
	1, // 1: sine.SineEngine.Filter:output_type -> sine.SineResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sine_proto_init() }
func file_sine_proto_init() {
	if File_sine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sine_proto_rawDesc), len(file_sine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sine_proto_goTypes,
		DependencyIndexes: file_sine_proto_depIdxs,
		MessageInfos:      file_sine_proto_msgTypes,
	}.Build()
	File_sine_proto = out.File
	file_sine_proto_goTypes = nil
	file_sine_proto_depIdxs = nil
}
