// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/ransomeye.proto

package ransomeyepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EmitterType matches Mishka PRD-03 identity_bytes encoding.
type EmitterType int32

const (
	EmitterType_EMITTER_TYPE_UNSPECIFIED EmitterType = 0
	EmitterType_EMITTER_TYPE_AGENT       EmitterType = 1
	EmitterType_EMITTER_TYPE_PROBE       EmitterType = 2
)

// Enum value maps for EmitterType.
var (
	EmitterType_name = map[int32]string{
		0: "EMITTER_TYPE_UNSPECIFIED",
		1: "EMITTER_TYPE_AGENT",
		2: "EMITTER_TYPE_PROBE",
	}
	EmitterType_value = map[string]int32{
		"EMITTER_TYPE_UNSPECIFIED": 0,
		"EMITTER_TYPE_AGENT":       1,
		"EMITTER_TYPE_PROBE":       2,
	}
)

func (x EmitterType) Enum() *EmitterType {
	p := new(EmitterType)
	*p = x
	return p
}

func (x EmitterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmitterType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ransomeye_proto_enumTypes[0].Descriptor()
}

func (EmitterType) Type() protoreflect.EnumType {
	return &file_proto_ransomeye_proto_enumTypes[0]
}

func (x EmitterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmitterType.Descriptor instead.
func (EmitterType) EnumDescriptor() ([]byte, []int) {
	return file_proto_ransomeye_proto_rawDescGZIP(), []int{0}
}

type ActionType int32

const (
	ActionType_KILL_PROCESS    ActionType = 0
	ActionType_BLOCK_IP        ActionType = 1
	ActionType_ISOLATE_HOST    ActionType = 2
	ActionType_SNAPSHOT_MEMORY ActionType = 3 // V0.0: warn! no-op
	ActionType_ALERT_ONLY      ActionType = 4
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "KILL_PROCESS",
		1: "BLOCK_IP",
		2: "ISOLATE_HOST",
		3: "SNAPSHOT_MEMORY",
		4: "ALERT_ONLY",
	}
	ActionType_value = map[string]int32{
		"KILL_PROCESS":    0,
		"BLOCK_IP":        1,
		"ISOLATE_HOST":    2,
		"SNAPSHOT_MEMORY": 3,
		"ALERT_ONLY":      4,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ransomeye_proto_enumTypes[1].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_proto_ransomeye_proto_enumTypes[1]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_ransomeye_proto_rawDescGZIP(), []int{1}
}

type ActionStatus int32

const (
	ActionStatus_PENDING    ActionStatus = 0
	ActionStatus_DISPATCHED ActionStatus = 1
	ActionStatus_EXECUTING  ActionStatus = 2
	ActionStatus_COMPLETED  ActionStatus = 3
	ActionStatus_FAILED     ActionStatus = 4
)

// Enum value maps for ActionStatus.
var (
	ActionStatus_name = map[int32]string{
		0: "PENDING",
		1: "DISPATCHED",
		2: "EXECUTING",
		3: "COMPLETED",
		4: "FAILED",
	}
	ActionStatus_value = map[string]int32{
		"PENDING":    0,
		"DISPATCHED": 1,
		"EXECUTING":  2,
		"COMPLETED":  3,
		"FAILED":     4,
	}
)

func (x ActionStatus) Enum() *ActionStatus {
	p := new(ActionStatus)
	*p = x
	return p
}

func (x ActionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ransomeye_proto_enumTypes[2].Descriptor()
}

func (ActionStatus) Type() protoreflect.EnumType {
	return &file_proto_ransomeye_proto_enumTypes[2]
}

func (x ActionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionStatus.Descriptor instead.
func (ActionStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_ransomeye_proto_rawDescGZIP(), []int{2}
}

type HandshakeRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AgentUuid           string                 `protobuf:"bytes,1,opt,name=agent_uuid,json=agentUuid,proto3" json:"agent_uuid,omitempty"`
	Hostname            string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	PrimaryIp           string                 `protobuf:"bytes,3,opt,name=primary_ip,json=primaryIp,proto3" json:"primary_ip,omitempty"`
	BootSessionId       string                 `protobuf:"bytes,4,opt,name=boot_session_id,json=bootSessionId,proto3" json:"boot_session_id,omitempty"` // UUID v4 from CSPRNG (PRD-00 §11.12)
	TpmQuote            []byte                 `protobuf:"bytes,5,opt,name=tpm_quote,json=tpmQuote,proto3" json:"tpm_quote,omitempty"`
	TpmPcrValues        []byte                 `protobuf:"bytes,6,opt,name=tpm_pcr_values,json=tpmPcrValues,proto3" json:"tpm_pcr_values,omitempty"`
	LogicalClock        int64                  `protobuf:"varint,7,opt,name=logical_clock,json=logicalClock,proto3" json:"logical_clock,omitempty"`
	AgentVersion        string                 `protobuf:"bytes,8,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	BinaryHash          []byte                 `protobuf:"bytes,9,opt,name=binary_hash,json=binaryHash,proto3" json:"binary_hash,omitempty"` // SHA-256 of agent binary
	OsType              string                 `protobuf:"bytes,10,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`
	OsVersion           string                 `protobuf:"bytes,11,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	AgentProtoVersion   string                 `protobuf:"bytes,20,opt,name=agent_proto_version,json=agentProtoVersion,proto3" json:"agent_proto_version,omitempty"` // Version negotiation
	MinSupportedByAgent string                 `protobuf:"bytes,21,opt,name=min_supported_by_agent,json=minSupportedByAgent,proto3" json:"min_supported_by_agent,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_proto_ransomeye_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ransomeye_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_proto_ransomeye_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeRequest) GetAgentUuid() string {
	if x != nil {
		return x.AgentUuid
	}
	return ""
}

func (x *HandshakeRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HandshakeRequest) GetPrimaryIp() string {
	if x != nil {
		return x.PrimaryIp
	}
	return ""
}

func (x *HandshakeRequest) GetBootSessionId() string {
	if x != nil {
		return x.BootSessionId
	}
	return ""
}

func (x *HandshakeRequest) GetTpmQuote() []byte {
	if x != nil {
		return x.TpmQuote
	}
	return nil
}

func (x *HandshakeRequest) GetTpmPcrValues() []byte {
	if x != nil {
		return x.TpmPcrValues
	}
	return nil
}

func (x *HandshakeRequest) GetLogicalClock() int64 {
	if x != nil {
		return x.LogicalClock
	}
	return 0
}

func (x *HandshakeRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *HandshakeRequest) GetBinaryHash() []byte {
	if x != nil {
		return x.BinaryHash
	}
	return nil
}

func (x *HandshakeRequest) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *HandshakeRequest) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *HandshakeRequest) GetAgentProtoVersion() string {
	if x != nil {
		return x.AgentProtoVersion
	}
	return ""
}

func (x *HandshakeRequest) GetMinSupportedByAgent() string {
	if x != nil {
		return x.MinSupportedByAgent
	}
	return ""
}

type HandshakeResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SessionToken       string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"` // UUID v4, memory-only
	ServerClock        int64                  `protobuf:"varint,2,opt,name=server_clock,json=serverClock,proto3" json:"server_clock,omitempty"`
	Accepted           bool                   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectReason       string                 `protobuf:"bytes,4,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	CoreProtoVersion   string                 `protobuf:"bytes,10,opt,name=core_proto_version,json=coreProtoVersion,proto3" json:"core_proto_version,omitempty"`
	MinSupportedByCore string                 `protobuf:"bytes,11,opt,name=min_supported_by_core,json=minSupportedByCore,proto3" json:"min_supported_by_core,omitempty"`
	AgentIsDeprecated  bool                   `protobuf:"varint,12,opt,name=agent_is_deprecated,json=agentIsDeprecated,proto3" json:"agent_is_deprecated,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_proto_ransomeye_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ransomeye_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_proto_ransomeye_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *HandshakeResponse) GetServerClock() int64 {
	if x != nil {
		return x.ServerClock
	}
	return 0
}

func (x *HandshakeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HandshakeResponse) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *HandshakeResponse) GetCoreProtoVersion() string {
	if x != nil {
		return x.CoreProtoVersion
	}
	return ""
}

func (x *HandshakeResponse) GetMinSupportedByCore() string {
	if x != nil {
		return x.MinSupportedByCore
	}
	return ""
}

func (x *HandshakeResponse) GetAgentIsDeprecated() bool {
	if x != nil {
		return x.AgentIsDeprecated
	}
	return false
}

// TelemetryEnvelope — trust-bearing ingress schema for pre-queue verification.
type TelemetryEnvelope struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MessageId          string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SigningContext     string                 `protobuf:"bytes,2,opt,name=signing_context,json=signingContext,proto3" json:"signing_context,omitempty"`
	Signature          []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	SystemIdentityHash string                 `protobuf:"bytes,4,opt,name=system_identity_hash,json=systemIdentityHash,proto3" json:"system_identity_hash,omitempty"`
	BootSessionId      string                 `protobuf:"bytes,5,opt,name=boot_session_id,json=bootSessionId,proto3" json:"boot_session_id,omitempty"`
	Payload            []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"` // Canonicalized payload bytes.
	AgentId            string                 `protobuf:"bytes,7,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ProbeId            string                 `protobuf:"bytes,8,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TelemetryEnvelope) Reset() {
	*x = TelemetryEnvelope{}
	mi := &file_proto_ransomeye_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryEnvelope) ProtoMessage() {}

func (x *TelemetryEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ransomeye_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryEnvelope.ProtoReflect.Descriptor instead.
func (*TelemetryEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_ransomeye_proto_rawDescGZIP(), []int{2}
}

func (x *TelemetryEnvelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *TelemetryEnvelope) GetSigningContext() string {
	if x != nil {
		return x.SigningContext
	}
	return ""
}

func (x *TelemetryEnvelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *TelemetryEnvelope) GetSystemIdentityHash() string {
	if x != nil {
		return x.SystemIdentityHash
	}
	return ""
}

func (x *TelemetryEnvelope) GetBootSessionId() string {
	if x != nil {
		return x.BootSessionId
	}
	return ""
}

func (x *TelemetryEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TelemetryEnvelope) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TelemetryEnvelope) GetProbeId() string {
	if x != nil {
		return x.ProbeId
	}
	return ""
}

type TelemetryAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ServerClock   int64                  `protobuf:"varint,2,opt,name=server_clock,json=serverClock,proto3" json:"server_clock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryAck) Reset() {
	*x = TelemetryAck{}
	mi := &file_proto_ransomeye_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryAck) ProtoMessage() {}

func (x *TelemetryAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ransomeye_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryAck.ProtoReflect.Descriptor instead.
func (*TelemetryAck) Descriptor() ([]byte, []int) {
	return file_proto_ransomeye_proto_rawDescGZIP(), []int{3}
}

func (x *TelemetryAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *TelemetryAck) GetServerClock() int64 {
	if x != nil {
		return x.ServerClock
	}
	return 0
}

// SignalEnvelope is the Mishka PRD-03 message envelope for canonical JSON payloads.
//
// Encoding rules:
// - hex fields MUST be lowercase and fixed-width (no UUID strings)
// - canonical_payload_json MUST be RFC8785 canonical JSON bytes (JCS)
type SignalEnvelope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	SigningContext  string                 `protobuf:"bytes,2,opt,name=signing_context,json=signingContext,proto3" json:"signing_context,omitempty"`
	// system_id (PRD-03): 32 bytes, lowercase hex (64 chars). Legacy field name is system_identity_hash.
	SystemId        string      `protobuf:"bytes,3,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	IdentityVersion uint32      `protobuf:"varint,4,opt,name=identity_version,json=identityVersion,proto3" json:"identity_version,omitempty"`                // current = 1 (0x01)
	EmitterType     EmitterType `protobuf:"varint,5,opt,name=emitter_type,json=emitterType,proto3,enum=ransomeye.EmitterType" json:"emitter_type,omitempty"` // agent | probe
	EmitterId       string      `protobuf:"bytes,6,opt,name=emitter_id,json=emitterId,proto3" json:"emitter_id,omitempty"`                                   // TRUNC128 identity bytes, lowercase hex (32 chars)
	// boot_session_id (PRD-03): 32 bytes, lowercase hex (64 chars)
	BootSessionId string `protobuf:"bytes,7,opt,name=boot_session_id,json=bootSessionId,proto3" json:"boot_session_id,omitempty"`
	LogicalClock  uint64 `protobuf:"varint,8,opt,name=logical_clock,json=logicalClock,proto3" json:"logical_clock,omitempty"` // UINT64
	// Derived fields (PRD-03 / PRD-08):
	PartitionContext string `protobuf:"bytes,9,opt,name=partition_context,json=partitionContext,proto3" json:"partition_context,omitempty"` // TRUNC128(SHA256(canonical_payload_bytes || identity_bytes)), lowercase hex (32 chars)
	PayloadHash      string `protobuf:"bytes,10,opt,name=payload_hash,json=payloadHash,proto3" json:"payload_hash,omitempty"`               // SHA256(canonical_payload_json), lowercase hex (64 chars)
	MessageId        string `protobuf:"bytes,11,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`                     // SHA256(...), lowercase hex (64 chars)
	// Ed25519 signature bytes (64 bytes).
	Signature []byte `protobuf:"bytes,12,opt,name=signature,proto3" json:"signature,omitempty"`
	// Canonical payload bytes (RFC8785 canonical JSON).
	CanonicalPayloadJson []byte `protobuf:"bytes,13,opt,name=canonical_payload_json,json=canonicalPayloadJson,proto3" json:"canonical_payload_json,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SignalEnvelope) Reset() {
	*x = SignalEnvelope{}
	mi := &file_proto_ransomeye_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalEnvelope) ProtoMessage() {}

func (x *SignalEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ransomeye_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalEnvelope.ProtoReflect.Descriptor instead.
func (*SignalEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_ransomeye_proto_rawDescGZIP(), []int{4}
}

func (x *SignalEnvelope) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *SignalEnvelope) GetSigningContext() string {
	if x != nil {
		return x.SigningContext
	}
	return ""
}

func (x *SignalEnvelope) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *SignalEnvelope) GetIdentityVersion() uint32 {
	if x != nil {
		return x.IdentityVersion
	}
	return 0
}

func (x *SignalEnvelope) GetEmitterType() EmitterType {
	if x != nil {
		return x.EmitterType
	}
	return EmitterType_EMITTER_TYPE_UNSPECIFIED
}

func (x *SignalEnvelope) GetEmitterId() string {
	if x != nil {
		return x.EmitterId
	}
	return ""
}

func (x *SignalEnvelope) GetBootSessionId() string {
	if x != nil {
		return x.BootSessionId
	}
	return ""
}

func (x *SignalEnvelope) GetLogicalClock() uint64 {
	if x != nil {
		return x.LogicalClock
	}
	return 0
}

func (x *SignalEnvelope) GetPartitionContext() string {
	if x != nil {
		return x.PartitionContext
	}
	return ""
}

func (x *SignalEnvelope) GetPayloadHash() string {
	if x != nil {
		return x.PayloadHash
	}
	return ""
}

func (x *SignalEnvelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SignalEnvelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignalEnvelope) GetCanonicalPayloadJson() []byte {
	if x != nil {
		return x.CanonicalPayloadJson
	}
	return nil
}

type SignalAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ServerClock   int64                  `protobuf:"varint,2,opt,name=server_clock,json=serverClock,proto3" json:"server_clock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalAck) Reset() {
	*x = SignalAck{}
	mi := &file_proto_ransomeye_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalAck) ProtoMessage() {}

func (x *SignalAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ransomeye_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalAck.ProtoReflect.Descriptor instead.
func (*SignalAck) Descriptor() ([]byte, []int) {
	return file_proto_ransomeye_proto_rawDescGZIP(), []int{5}
}

func (x *SignalAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SignalAck) GetServerClock() int64 {
	if x != nil {
		return x.ServerClock
	}
	return 0
}

type HeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionToken   string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	CpuUsagePct    float32                `protobuf:"fixed32,3,opt,name=cpu_usage_pct,json=cpuUsagePct,proto3" json:"cpu_usage_pct,omitempty"`
	RamUsedMb      int64                  `protobuf:"varint,4,opt,name=ram_used_mb,json=ramUsedMb,proto3" json:"ram_used_mb,omitempty"`
	RamTotalMb     int64                  `protobuf:"varint,5,opt,name=ram_total_mb,json=ramTotalMb,proto3" json:"ram_total_mb,omitempty"`
	TopProcesses   string                 `protobuf:"bytes,6,opt,name=top_processes,json=topProcesses,proto3" json:"top_processes,omitempty"` // JSON top-5
	LoadAvg_1M     float32                `protobuf:"fixed32,7,opt,name=load_avg_1m,json=loadAvg1m,proto3" json:"load_avg_1m,omitempty"`
	TpmQuote       []byte                 `protobuf:"bytes,8,opt,name=tpm_quote,json=tpmQuote,proto3" json:"tpm_quote,omitempty"`
	BinaryHash     []byte                 `protobuf:"bytes,9,opt,name=binary_hash,json=binaryHash,proto3" json:"binary_hash,omitempty"`
	LogicalClock   int64                  `protobuf:"varint,10,opt,name=logical_clock,json=logicalClock,proto3" json:"logical_clock,omitempty"`
	WallClockEpoch int64                  `protobuf:"varint,11,opt,name=wall_clock_epoch,json=wallClockEpoch,proto3" json:"wall_clock_epoch,omitempty"`
	EventDropCount int64                  `protobuf:"varint,12,opt,name=event_drop_count,json=eventDropCount,proto3" json:"event_drop_count,omitempty"`
	BootSessionId  string                 `protobuf:"bytes,13,opt,name=boot_session_id,json=bootSessionId,proto3" json:"boot_session_id,omitempty"` // Ephemeral UUID v4
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_ransomeye_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ransomeye_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_ransomeye_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *HeartbeatRequest) GetCpuUsagePct() float32 {
	if x != nil {
		return x.CpuUsagePct
	}
	return 0
}

func (x *HeartbeatRequest) GetRamUsedMb() int64 {
	if x != nil {
		return x.RamUsedMb
	}
	return 0
}

func (x *HeartbeatRequest) GetRamTotalMb() int64 {
	if x != nil {
		return x.RamTotalMb
	}
	return 0
}

func (x *HeartbeatRequest) GetTopProcesses() string {
	if x != nil {
		return x.TopProcesses
	}
	return ""
}

func (x *HeartbeatRequest) GetLoadAvg_1M() float32 {
	if x != nil {
		return x.LoadAvg_1M
	}
	return 0
}

func (x *HeartbeatRequest) GetTpmQuote() []byte {
	if x != nil {
		return x.TpmQuote
	}
	return nil
}

func (x *HeartbeatRequest) GetBinaryHash() []byte {
	if x != nil {
		return x.BinaryHash
	}
	return nil
}

func (x *HeartbeatRequest) GetLogicalClock() int64 {
	if x != nil {
		return x.LogicalClock
	}
	return 0
}

func (x *HeartbeatRequest) GetWallClockEpoch() int64 {
	if x != nil {
		return x.WallClockEpoch
	}
	return 0
}

func (x *HeartbeatRequest) GetEventDropCount() int64 {
	if x != nil {
		return x.EventDropCount
	}
	return 0
}

func (x *HeartbeatRequest) GetBootSessionId() string {
	if x != nil {
		return x.BootSessionId
	}
	return ""
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerClock   int64                  `protobuf:"varint,1,opt,name=server_clock,json=serverClock,proto3" json:"server_clock,omitempty"`
	SessionValid  bool                   `protobuf:"varint,2,opt,name=session_valid,json=sessionValid,proto3" json:"session_valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_proto_ransomeye_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ransomeye_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_proto_ransomeye_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatAck) GetServerClock() int64 {
	if x != nil {
		return x.ServerClock
	}
	return 0
}

func (x *HeartbeatAck) GetSessionValid() bool {
	if x != nil {
		return x.SessionValid
	}
	return false
}

type ActionCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActionId       string                 `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	DetectionId    string                 `protobuf:"bytes,2,opt,name=detection_id,json=detectionId,proto3" json:"detection_id,omitempty"`
	ActionType     ActionType             `protobuf:"varint,3,opt,name=action_type,json=actionType,proto3,enum=ransomeye.ActionType" json:"action_type,omitempty"`
	ParametersJson string                 `protobuf:"bytes,4,opt,name=parameters_json,json=parametersJson,proto3" json:"parameters_json,omitempty"`
	LogicalClock   int64                  `protobuf:"varint,5,opt,name=logical_clock,json=logicalClock,proto3" json:"logical_clock,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActionCommand) Reset() {
	*x = ActionCommand{}
	mi := &file_proto_ransomeye_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionCommand) ProtoMessage() {}

func (x *ActionCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ransomeye_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionCommand.ProtoReflect.Descriptor instead.
func (*ActionCommand) Descriptor() ([]byte, []int) {
	return file_proto_ransomeye_proto_rawDescGZIP(), []int{8}
}

func (x *ActionCommand) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *ActionCommand) GetDetectionId() string {
	if x != nil {
		return x.DetectionId
	}
	return ""
}

func (x *ActionCommand) GetActionType() ActionType {
	if x != nil {
		return x.ActionType
	}
	return ActionType_KILL_PROCESS
}

func (x *ActionCommand) GetParametersJson() string {
	if x != nil {
		return x.ParametersJson
	}
	return ""
}

func (x *ActionCommand) GetLogicalClock() int64 {
	if x != nil {
		return x.LogicalClock
	}
	return 0
}

type ActionResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActionId       string                 `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	AgentId        string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status         ActionStatus           `protobuf:"varint,3,opt,name=status,proto3,enum=ransomeye.ActionStatus" json:"status,omitempty"`
	Success        bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	LogicalClock   int64                  `protobuf:"varint,6,opt,name=logical_clock,json=logicalClock,proto3" json:"logical_clock,omitempty"`
	WallClockEpoch int64                  `protobuf:"varint,7,opt,name=wall_clock_epoch,json=wallClockEpoch,proto3" json:"wall_clock_epoch,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActionResult) Reset() {
	*x = ActionResult{}
	mi := &file_proto_ransomeye_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResult) ProtoMessage() {}

func (x *ActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ransomeye_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResult.ProtoReflect.Descriptor instead.
func (*ActionResult) Descriptor() ([]byte, []int) {
	return file_proto_ransomeye_proto_rawDescGZIP(), []int{9}
}

func (x *ActionResult) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *ActionResult) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ActionResult) GetStatus() ActionStatus {
	if x != nil {
		return x.Status
	}
	return ActionStatus_PENDING
}

func (x *ActionResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ActionResult) GetLogicalClock() int64 {
	if x != nil {
		return x.LogicalClock
	}
	return 0
}

func (x *ActionResult) GetWallClockEpoch() int64 {
	if x != nil {
		return x.WallClockEpoch
	}
	return 0
}

type ActionAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionAck) Reset() {
	*x = ActionAck{}
	mi := &file_proto_ransomeye_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionAck) ProtoMessage() {}

func (x *ActionAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ransomeye_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionAck.ProtoReflect.Descriptor instead.
func (*ActionAck) Descriptor() ([]byte, []int) {
	return file_proto_ransomeye_proto_rawDescGZIP(), []int{10}
}

func (x *ActionAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type FlowBatch struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProbeId        string                 `protobuf:"bytes,1,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	Flows          []*Flow                `protobuf:"bytes,2,rep,name=flows,proto3" json:"flows,omitempty"` // Max 100 per batch
	LogicalClock   int64                  `protobuf:"varint,3,opt,name=logical_clock,json=logicalClock,proto3" json:"logical_clock,omitempty"`
	WallClockEpoch int64                  `protobuf:"varint,4,opt,name=wall_clock_epoch,json=wallClockEpoch,proto3" json:"wall_clock_epoch,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FlowBatch) Reset() {
	*x = FlowBatch{}
	mi := &file_proto_ransomeye_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowBatch) ProtoMessage() {}

func (x *FlowBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ransomeye_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowBatch.ProtoReflect.Descriptor instead.
func (*FlowBatch) Descriptor() ([]byte, []int) {
	return file_proto_ransomeye_proto_rawDescGZIP(), []int{11}
}

func (x *FlowBatch) GetProbeId() string {
	if x != nil {
		return x.ProbeId
	}
	return ""
}

func (x *FlowBatch) GetFlows() []*Flow {
	if x != nil {
		return x.Flows
	}
	return nil
}

func (x *FlowBatch) GetLogicalClock() int64 {
	if x != nil {
		return x.LogicalClock
	}
	return 0
}

func (x *FlowBatch) GetWallClockEpoch() int64 {
	if x != nil {
		return x.WallClockEpoch
	}
	return 0
}

type Flow struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SrcIp            string                 `protobuf:"bytes,1,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	DstIp            string                 `protobuf:"bytes,2,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	SrcPort          int32                  `protobuf:"varint,3,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstPort          int32                  `protobuf:"varint,4,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	Protocol         string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	BytesSent        int64                  `protobuf:"varint,6,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesRecv        int64                  `protobuf:"varint,7,opt,name=bytes_recv,json=bytesRecv,proto3" json:"bytes_recv,omitempty"`
	AppProto         string                 `protobuf:"bytes,8,opt,name=app_proto,json=appProto,proto3" json:"app_proto,omitempty"`
	Ja3Hash          string                 `protobuf:"bytes,9,opt,name=ja3_hash,json=ja3Hash,proto3" json:"ja3_hash,omitempty"` // String (not bytes)
	ExfilConfidence  float32                `protobuf:"fixed32,10,opt,name=exfil_confidence,json=exfilConfidence,proto3" json:"exfil_confidence,omitempty"`
	BeaconConfidence float32                `protobuf:"fixed32,11,opt,name=beacon_confidence,json=beaconConfidence,proto3" json:"beacon_confidence,omitempty"`
	ThreatMetadata   string                 `protobuf:"bytes,12,opt,name=threat_metadata,json=threatMetadata,proto3" json:"threat_metadata,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Flow) Reset() {
	*x = Flow{}
	mi := &file_proto_ransomeye_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flow) ProtoMessage() {}

func (x *Flow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ransomeye_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flow.ProtoReflect.Descriptor instead.
func (*Flow) Descriptor() ([]byte, []int) {
	return file_proto_ransomeye_proto_rawDescGZIP(), []int{12}
}

func (x *Flow) GetSrcIp() string {
	if x != nil {
		return x.SrcIp
	}
	return ""
}

func (x *Flow) GetDstIp() string {
	if x != nil {
		return x.DstIp
	}
	return ""
}

func (x *Flow) GetSrcPort() int32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *Flow) GetDstPort() int32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *Flow) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Flow) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *Flow) GetBytesRecv() int64 {
	if x != nil {
		return x.BytesRecv
	}
	return 0
}

func (x *Flow) GetAppProto() string {
	if x != nil {
		return x.AppProto
	}
	return ""
}

func (x *Flow) GetJa3Hash() string {
	if x != nil {
		return x.Ja3Hash
	}
	return ""
}

func (x *Flow) GetExfilConfidence() float32 {
	if x != nil {
		return x.ExfilConfidence
	}
	return 0
}

func (x *Flow) GetBeaconConfidence() float32 {
	if x != nil {
		return x.BeaconConfidence
	}
	return 0
}

func (x *Flow) GetThreatMetadata() string {
	if x != nil {
		return x.ThreatMetadata
	}
	return ""
}

type DPIDetectionEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProbeId         string                 `protobuf:"bytes,1,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	BootSessionId   string                 `protobuf:"bytes,12,opt,name=boot_session_id,json=bootSessionId,proto3" json:"boot_session_id,omitempty"` // UUID v4 at startup, not persisted (PRD-00 §11.12)
	SchemaVersion   uint32                 `protobuf:"varint,13,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`  // must be 1
	DetectionType   string                 `protobuf:"bytes,2,opt,name=detection_type,json=detectionType,proto3" json:"detection_type,omitempty"`
	SrcIp           string                 `protobuf:"bytes,3,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	DstIp           string                 `protobuf:"bytes,4,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	SrcPort         int32                  `protobuf:"varint,5,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstPort         int32                  `protobuf:"varint,6,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	Confidence      float32                `protobuf:"fixed32,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	DetailJson      string                 `protobuf:"bytes,8,opt,name=detail_json,json=detailJson,proto3" json:"detail_json,omitempty"`
	RawEvidenceJson string                 `protobuf:"bytes,9,opt,name=raw_evidence_json,json=rawEvidenceJson,proto3" json:"raw_evidence_json,omitempty"`
	LogicalClock    int64                  `protobuf:"varint,10,opt,name=logical_clock,json=logicalClock,proto3" json:"logical_clock,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DPIDetectionEvent) Reset() {
	*x = DPIDetectionEvent{}
	mi := &file_proto_ransomeye_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DPIDetectionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DPIDetectionEvent) ProtoMessage() {}

func (x *DPIDetectionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ransomeye_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DPIDetectionEvent.ProtoReflect.Descriptor instead.
func (*DPIDetectionEvent) Descriptor() ([]byte, []int) {
	return file_proto_ransomeye_proto_rawDescGZIP(), []int{13}
}

func (x *DPIDetectionEvent) GetProbeId() string {
	if x != nil {
		return x.ProbeId
	}
	return ""
}

func (x *DPIDetectionEvent) GetBootSessionId() string {
	if x != nil {
		return x.BootSessionId
	}
	return ""
}

func (x *DPIDetectionEvent) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *DPIDetectionEvent) GetDetectionType() string {
	if x != nil {
		return x.DetectionType
	}
	return ""
}

func (x *DPIDetectionEvent) GetSrcIp() string {
	if x != nil {
		return x.SrcIp
	}
	return ""
}

func (x *DPIDetectionEvent) GetDstIp() string {
	if x != nil {
		return x.DstIp
	}
	return ""
}

func (x *DPIDetectionEvent) GetSrcPort() int32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *DPIDetectionEvent) GetDstPort() int32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *DPIDetectionEvent) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *DPIDetectionEvent) GetDetailJson() string {
	if x != nil {
		return x.DetailJson
	}
	return ""
}

func (x *DPIDetectionEvent) GetRawEvidenceJson() string {
	if x != nil {
		return x.RawEvidenceJson
	}
	return ""
}

func (x *DPIDetectionEvent) GetLogicalClock() int64 {
	if x != nil {
		return x.LogicalClock
	}
	return 0
}

// NOTE: PRD-13 defines the RPC but does not define fields for this request message.
type ActionStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionStreamRequest) Reset() {
	*x = ActionStreamRequest{}
	mi := &file_proto_ransomeye_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionStreamRequest) ProtoMessage() {}

func (x *ActionStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ransomeye_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionStreamRequest.ProtoReflect.Descriptor instead.
func (*ActionStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_ransomeye_proto_rawDescGZIP(), []int{14}
}

// NOTE: PRD-13 defines the RPC but does not define fields for this ack message.
type FlowAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowAck) Reset() {
	*x = FlowAck{}
	mi := &file_proto_ransomeye_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowAck) ProtoMessage() {}

func (x *FlowAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ransomeye_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowAck.ProtoReflect.Descriptor instead.
func (*FlowAck) Descriptor() ([]byte, []int) {
	return file_proto_ransomeye_proto_rawDescGZIP(), []int{15}
}

// NOTE: PRD-13 defines the RPC but does not define fields for this ack message.
type DPIEventAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DPIEventAck) Reset() {
	*x = DPIEventAck{}
	mi := &file_proto_ransomeye_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DPIEventAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DPIEventAck) ProtoMessage() {}

func (x *DPIEventAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ransomeye_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DPIEventAck.ProtoReflect.Descriptor instead.
func (*DPIEventAck) Descriptor() ([]byte, []int) {
	return file_proto_ransomeye_proto_rawDescGZIP(), []int{16}
}

// PRD-13 (text) defines fields but does not provide field numbers; assigned sequentially in listed order.
type ProbeRegistration struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProbeId        string                 `protobuf:"bytes,1,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	ProbeType      string                 `protobuf:"bytes,2,opt,name=probe_type,json=probeType,proto3" json:"probe_type,omitempty"`
	Hostname       string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	CoveredSubnets []string               `protobuf:"bytes,4,rep,name=covered_subnets,json=coveredSubnets,proto3" json:"covered_subnets,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProbeRegistration) Reset() {
	*x = ProbeRegistration{}
	mi := &file_proto_ransomeye_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeRegistration) ProtoMessage() {}

func (x *ProbeRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ransomeye_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeRegistration.ProtoReflect.Descriptor instead.
func (*ProbeRegistration) Descriptor() ([]byte, []int) {
	return file_proto_ransomeye_proto_rawDescGZIP(), []int{17}
}

func (x *ProbeRegistration) GetProbeId() string {
	if x != nil {
		return x.ProbeId
	}
	return ""
}

func (x *ProbeRegistration) GetProbeType() string {
	if x != nil {
		return x.ProbeType
	}
	return ""
}

func (x *ProbeRegistration) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ProbeRegistration) GetCoveredSubnets() []string {
	if x != nil {
		return x.CoveredSubnets
	}
	return nil
}

// PRD-13 defines the RPC but does not define fields for this ack message.
type ProbeRegistrationAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeRegistrationAck) Reset() {
	*x = ProbeRegistrationAck{}
	mi := &file_proto_ransomeye_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeRegistrationAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeRegistrationAck) ProtoMessage() {}

func (x *ProbeRegistrationAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ransomeye_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeRegistrationAck.ProtoReflect.Descriptor instead.
func (*ProbeRegistrationAck) Descriptor() ([]byte, []int) {
	return file_proto_ransomeye_proto_rawDescGZIP(), []int{18}
}

// PRD-13 defines the RPC but does not define fields for this request message.
type ProbeHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeHeartbeatRequest) Reset() {
	*x = ProbeHeartbeatRequest{}
	mi := &file_proto_ransomeye_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeHeartbeatRequest) ProtoMessage() {}

func (x *ProbeHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ransomeye_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*ProbeHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_ransomeye_proto_rawDescGZIP(), []int{19}
}

// PRD-13 defines the RPC but does not define fields for this ack message.
type ProbeHeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeHeartbeatAck) Reset() {
	*x = ProbeHeartbeatAck{}
	mi := &file_proto_ransomeye_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeHeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeHeartbeatAck) ProtoMessage() {}

func (x *ProbeHeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ransomeye_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeHeartbeatAck.ProtoReflect.Descriptor instead.
func (*ProbeHeartbeatAck) Descriptor() ([]byte, []int) {
	return file_proto_ransomeye_proto_rawDescGZIP(), []int{20}
}

// PRD-13 defines the RPC but does not define fields for this request message.
type PullConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullConfigRequest) Reset() {
	*x = PullConfigRequest{}
	mi := &file_proto_ransomeye_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullConfigRequest) ProtoMessage() {}

func (x *PullConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ransomeye_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullConfigRequest.ProtoReflect.Descriptor instead.
func (*PullConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_ransomeye_proto_rawDescGZIP(), []int{21}
}

// PRD-13 defines the RPC but does not define fields for this response message.
type ProbeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeConfig) Reset() {
	*x = ProbeConfig{}
	mi := &file_proto_ransomeye_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeConfig) ProtoMessage() {}

func (x *ProbeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ransomeye_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeConfig.ProtoReflect.Descriptor instead.
func (*ProbeConfig) Descriptor() ([]byte, []int) {
	return file_proto_ransomeye_proto_rawDescGZIP(), []int{22}
}

// PRD-13 (text) defines fields but does not provide field numbers; assigned sequentially in listed order.
type NetworkInfraFinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FindingType   string                 `protobuf:"bytes,1,opt,name=finding_type,json=findingType,proto3" json:"finding_type,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"` // score ∈ [0,1]
	SourceIp      string                 `protobuf:"bytes,3,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	DetailJson    string                 `protobuf:"bytes,4,opt,name=detail_json,json=detailJson,proto3" json:"detail_json,omitempty"`
	LogicalClock  int64                  `protobuf:"varint,5,opt,name=logical_clock,json=logicalClock,proto3" json:"logical_clock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInfraFinding) Reset() {
	*x = NetworkInfraFinding{}
	mi := &file_proto_ransomeye_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInfraFinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInfraFinding) ProtoMessage() {}

func (x *NetworkInfraFinding) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ransomeye_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInfraFinding.ProtoReflect.Descriptor instead.
func (*NetworkInfraFinding) Descriptor() ([]byte, []int) {
	return file_proto_ransomeye_proto_rawDescGZIP(), []int{23}
}

func (x *NetworkInfraFinding) GetFindingType() string {
	if x != nil {
		return x.FindingType
	}
	return ""
}

func (x *NetworkInfraFinding) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *NetworkInfraFinding) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *NetworkInfraFinding) GetDetailJson() string {
	if x != nil {
		return x.DetailJson
	}
	return ""
}

func (x *NetworkInfraFinding) GetLogicalClock() int64 {
	if x != nil {
		return x.LogicalClock
	}
	return 0
}

// PRD-13 defines the RPC but does not define fields for this ack message.
type FindingAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindingAck) Reset() {
	*x = FindingAck{}
	mi := &file_proto_ransomeye_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindingAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindingAck) ProtoMessage() {}

func (x *FindingAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ransomeye_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindingAck.ProtoReflect.Descriptor instead.
func (*FindingAck) Descriptor() ([]byte, []int) {
	return file_proto_ransomeye_proto_rawDescGZIP(), []int{24}
}

var File_proto_ransomeye_proto protoreflect.FileDescriptor

const file_proto_ransomeye_proto_rawDesc = "" +
	"\n" +
	"\x15proto/ransomeye.proto\x12\transomeye\"\xdf\x03\n" +
	"\x10HandshakeRequest\x12\x1d\n" +
	"\n" +
	"agent_uuid\x18\x01 \x01(\tR\tagentUuid\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"primary_ip\x18\x03 \x01(\tR\tprimaryIp\x12&\n" +
	"\x0fboot_session_id\x18\x04 \x01(\tR\rbootSessionId\x12\x1b\n" +
	"\ttpm_quote\x18\x05 \x01(\fR\btpmQuote\x12$\n" +
	"\x0etpm_pcr_values\x18\x06 \x01(\fR\ftpmPcrValues\x12#\n" +
	"\rlogical_clock\x18\a \x01(\x03R\flogicalClock\x12#\n" +
	"\ragent_version\x18\b \x01(\tR\fagentVersion\x12\x1f\n" +
	"\vbinary_hash\x18\t \x01(\fR\n" +
	"binaryHash\x12\x17\n" +
	"\aos_type\x18\n" +
	" \x01(\tR\x06osType\x12\x1d\n" +
	"\n" +
	"os_version\x18\v \x01(\tR\tosVersion\x12.\n" +
	"\x13agent_proto_version\x18\x14 \x01(\tR\x11agentProtoVersion\x123\n" +
	"\x16min_supported_by_agent\x18\x15 \x01(\tR\x13minSupportedByAgent\"\xad\x02\n" +
	"\x11HandshakeResponse\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\x12!\n" +
	"\fserver_clock\x18\x02 \x01(\x03R\vserverClock\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\bR\baccepted\x12#\n" +
	"\rreject_reason\x18\x04 \x01(\tR\frejectReason\x12,\n" +
	"\x12core_proto_version\x18\n" +
	" \x01(\tR\x10coreProtoVersion\x121\n" +
	"\x15min_supported_by_core\x18\v \x01(\tR\x12minSupportedByCore\x12.\n" +
	"\x13agent_is_deprecated\x18\f \x01(\bR\x11agentIsDeprecated\"\xa3\x02\n" +
	"\x11TelemetryEnvelope\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12'\n" +
	"\x0fsigning_context\x18\x02 \x01(\tR\x0esigningContext\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x120\n" +
	"\x14system_identity_hash\x18\x04 \x01(\tR\x12systemIdentityHash\x12&\n" +
	"\x0fboot_session_id\x18\x05 \x01(\tR\rbootSessionId\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12\x19\n" +
	"\bagent_id\x18\a \x01(\tR\aagentId\x12\x19\n" +
	"\bprobe_id\x18\b \x01(\tR\aprobeId\"M\n" +
	"\fTelemetryAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12!\n" +
	"\fserver_clock\x18\x02 \x01(\x03R\vserverClock\"\x96\x04\n" +
	"\x0eSignalEnvelope\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12'\n" +
	"\x0fsigning_context\x18\x02 \x01(\tR\x0esigningContext\x12\x1b\n" +
	"\tsystem_id\x18\x03 \x01(\tR\bsystemId\x12)\n" +
	"\x10identity_version\x18\x04 \x01(\rR\x0fidentityVersion\x129\n" +
	"\femitter_type\x18\x05 \x01(\x0e2\x16.ransomeye.EmitterTypeR\vemitterType\x12\x1d\n" +
	"\n" +
	"emitter_id\x18\x06 \x01(\tR\temitterId\x12&\n" +
	"\x0fboot_session_id\x18\a \x01(\tR\rbootSessionId\x12#\n" +
	"\rlogical_clock\x18\b \x01(\x04R\flogicalClock\x12+\n" +
	"\x11partition_context\x18\t \x01(\tR\x10partitionContext\x12!\n" +
	"\fpayload_hash\x18\n" +
	" \x01(\tR\vpayloadHash\x12\x1d\n" +
	"\n" +
	"message_id\x18\v \x01(\tR\tmessageId\x12\x1c\n" +
	"\tsignature\x18\f \x01(\fR\tsignature\x124\n" +
	"\x16canonical_payload_json\x18\r \x01(\fR\x14canonicalPayloadJson\"J\n" +
	"\tSignalAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12!\n" +
	"\fserver_clock\x18\x02 \x01(\x03R\vserverClock\"\xdc\x03\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x12\"\n" +
	"\rcpu_usage_pct\x18\x03 \x01(\x02R\vcpuUsagePct\x12\x1e\n" +
	"\vram_used_mb\x18\x04 \x01(\x03R\tramUsedMb\x12 \n" +
	"\fram_total_mb\x18\x05 \x01(\x03R\n" +
	"ramTotalMb\x12#\n" +
	"\rtop_processes\x18\x06 \x01(\tR\ftopProcesses\x12\x1e\n" +
	"\vload_avg_1m\x18\a \x01(\x02R\tloadAvg1m\x12\x1b\n" +
	"\ttpm_quote\x18\b \x01(\fR\btpmQuote\x12\x1f\n" +
	"\vbinary_hash\x18\t \x01(\fR\n" +
	"binaryHash\x12#\n" +
	"\rlogical_clock\x18\n" +
	" \x01(\x03R\flogicalClock\x12(\n" +
	"\x10wall_clock_epoch\x18\v \x01(\x03R\x0ewallClockEpoch\x12(\n" +
	"\x10event_drop_count\x18\f \x01(\x03R\x0eeventDropCount\x12&\n" +
	"\x0fboot_session_id\x18\r \x01(\tR\rbootSessionId\"V\n" +
	"\fHeartbeatAck\x12!\n" +
	"\fserver_clock\x18\x01 \x01(\x03R\vserverClock\x12#\n" +
	"\rsession_valid\x18\x02 \x01(\bR\fsessionValid\"\xd5\x01\n" +
	"\rActionCommand\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\tR\bactionId\x12!\n" +
	"\fdetection_id\x18\x02 \x01(\tR\vdetectionId\x126\n" +
	"\vaction_type\x18\x03 \x01(\x0e2\x15.ransomeye.ActionTypeR\n" +
	"actionType\x12'\n" +
	"\x0fparameters_json\x18\x04 \x01(\tR\x0eparametersJson\x12#\n" +
	"\rlogical_clock\x18\x05 \x01(\x03R\flogicalClock\"\x85\x02\n" +
	"\fActionResult\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\tR\bactionId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12/\n" +
	"\x06status\x18\x03 \x01(\x0e2\x17.ransomeye.ActionStatusR\x06status\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12#\n" +
	"\rlogical_clock\x18\x06 \x01(\x03R\flogicalClock\x12(\n" +
	"\x10wall_clock_epoch\x18\a \x01(\x03R\x0ewallClockEpoch\"'\n" +
	"\tActionAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\x9c\x01\n" +
	"\tFlowBatch\x12\x19\n" +
	"\bprobe_id\x18\x01 \x01(\tR\aprobeId\x12%\n" +
	"\x05flows\x18\x02 \x03(\v2\x0f.ransomeye.FlowR\x05flows\x12#\n" +
	"\rlogical_clock\x18\x03 \x01(\x03R\flogicalClock\x12(\n" +
	"\x10wall_clock_epoch\x18\x04 \x01(\x03R\x0ewallClockEpoch\"\xfd\x02\n" +
	"\x04Flow\x12\x15\n" +
	"\x06src_ip\x18\x01 \x01(\tR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\x02 \x01(\tR\x05dstIp\x12\x19\n" +
	"\bsrc_port\x18\x03 \x01(\x05R\asrcPort\x12\x19\n" +
	"\bdst_port\x18\x04 \x01(\x05R\adstPort\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x06 \x01(\x03R\tbytesSent\x12\x1d\n" +
	"\n" +
	"bytes_recv\x18\a \x01(\x03R\tbytesRecv\x12\x1b\n" +
	"\tapp_proto\x18\b \x01(\tR\bappProto\x12\x19\n" +
	"\bja3_hash\x18\t \x01(\tR\aja3Hash\x12)\n" +
	"\x10exfil_confidence\x18\n" +
	" \x01(\x02R\x0fexfilConfidence\x12+\n" +
	"\x11beacon_confidence\x18\v \x01(\x02R\x10beaconConfidence\x12'\n" +
	"\x0fthreat_metadata\x18\f \x01(\tR\x0ethreatMetadata\"\x9a\x03\n" +
	"\x11DPIDetectionEvent\x12\x19\n" +
	"\bprobe_id\x18\x01 \x01(\tR\aprobeId\x12&\n" +
	"\x0fboot_session_id\x18\f \x01(\tR\rbootSessionId\x12%\n" +
	"\x0eschema_version\x18\r \x01(\rR\rschemaVersion\x12%\n" +
	"\x0edetection_type\x18\x02 \x01(\tR\rdetectionType\x12\x15\n" +
	"\x06src_ip\x18\x03 \x01(\tR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\x04 \x01(\tR\x05dstIp\x12\x19\n" +
	"\bsrc_port\x18\x05 \x01(\x05R\asrcPort\x12\x19\n" +
	"\bdst_port\x18\x06 \x01(\x05R\adstPort\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x02R\n" +
	"confidence\x12\x1f\n" +
	"\vdetail_json\x18\b \x01(\tR\n" +
	"detailJson\x12*\n" +
	"\x11raw_evidence_json\x18\t \x01(\tR\x0frawEvidenceJson\x12#\n" +
	"\rlogical_clock\x18\n" +
	" \x01(\x03R\flogicalClock\"\x15\n" +
	"\x13ActionStreamRequest\"\t\n" +
	"\aFlowAck\"\r\n" +
	"\vDPIEventAck\"\x92\x01\n" +
	"\x11ProbeRegistration\x12\x19\n" +
	"\bprobe_id\x18\x01 \x01(\tR\aprobeId\x12\x1d\n" +
	"\n" +
	"probe_type\x18\x02 \x01(\tR\tprobeType\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12'\n" +
	"\x0fcovered_subnets\x18\x04 \x03(\tR\x0ecoveredSubnets\"\x16\n" +
	"\x14ProbeRegistrationAck\"\x17\n" +
	"\x15ProbeHeartbeatRequest\"\x13\n" +
	"\x11ProbeHeartbeatAck\"\x13\n" +
	"\x11PullConfigRequest\"\r\n" +
	"\vProbeConfig\"\xb1\x01\n" +
	"\x13NetworkInfraFinding\x12!\n" +
	"\ffinding_type\x18\x01 \x01(\tR\vfindingType\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12\x1b\n" +
	"\tsource_ip\x18\x03 \x01(\tR\bsourceIp\x12\x1f\n" +
	"\vdetail_json\x18\x04 \x01(\tR\n" +
	"detailJson\x12#\n" +
	"\rlogical_clock\x18\x05 \x01(\x03R\flogicalClock\"\f\n" +
	"\n" +
	"FindingAck*[\n" +
	"\vEmitterType\x12\x1c\n" +
	"\x18EMITTER_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EMITTER_TYPE_AGENT\x10\x01\x12\x16\n" +
	"\x12EMITTER_TYPE_PROBE\x10\x02*c\n" +
	"\n" +
	"ActionType\x12\x10\n" +
	"\fKILL_PROCESS\x10\x00\x12\f\n" +
	"\bBLOCK_IP\x10\x01\x12\x10\n" +
	"\fISOLATE_HOST\x10\x02\x12\x13\n" +
	"\x0fSNAPSHOT_MEMORY\x10\x03\x12\x0e\n" +
	"\n" +
	"ALERT_ONLY\x10\x04*U\n" +
	"\fActionStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\x0e\n" +
	"\n" +
	"DISPATCHED\x10\x01\x12\r\n" +
	"\tEXECUTING\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x042\xbd\x04\n" +
	"\x10RansomEyeService\x12F\n" +
	"\tHandshake\x12\x1b.ransomeye.HandshakeRequest\x1a\x1c.ransomeye.HandshakeResponse\x12F\n" +
	"\rSendTelemetry\x12\x1c.ransomeye.TelemetryEnvelope\x1a\x17.ransomeye.TelemetryAck\x12=\n" +
	"\n" +
	"SendSignal\x12\x19.ransomeye.SignalEnvelope\x1a\x14.ransomeye.SignalAck\x12E\n" +
	"\rSendHeartbeat\x12\x1b.ransomeye.HeartbeatRequest\x1a\x17.ransomeye.HeartbeatAck\x12L\n" +
	"\x0eReceiveActions\x12\x1e.ransomeye.ActionStreamRequest\x1a\x18.ransomeye.ActionCommand0\x01\x12C\n" +
	"\x12ReportActionResult\x12\x17.ransomeye.ActionResult\x1a\x14.ransomeye.ActionAck\x12:\n" +
	"\x0eSendFlowStream\x12\x14.ransomeye.FlowBatch\x1a\x12.ransomeye.FlowAck\x12D\n" +
	"\fSendDPIEvent\x12\x1c.ransomeye.DPIDetectionEvent\x1a\x16.ransomeye.DPIEventAck2\xbc\x02\n" +
	"\fProbeService\x12N\n" +
	"\rRegisterProbe\x12\x1c.ransomeye.ProbeRegistration\x1a\x1f.ransomeye.ProbeRegistrationAck\x12P\n" +
	"\x0eProbeHeartbeat\x12 .ransomeye.ProbeHeartbeatRequest\x1a\x1c.ransomeye.ProbeHeartbeatAck\x12B\n" +
	"\n" +
	"PullConfig\x12\x1c.ransomeye.PullConfigRequest\x1a\x16.ransomeye.ProbeConfig\x12F\n" +
	"\rReportFinding\x12\x1e.ransomeye.NetworkInfraFinding\x1a\x15.ransomeye.FindingAckB)Z'ransomeye/proto/ransomeyepb;ransomeyepbb\x06proto3"

var (
	file_proto_ransomeye_proto_rawDescOnce sync.Once
	file_proto_ransomeye_proto_rawDescData []byte
)

func file_proto_ransomeye_proto_rawDescGZIP() []byte {
	file_proto_ransomeye_proto_rawDescOnce.Do(func() {
		file_proto_ransomeye_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ransomeye_proto_rawDesc), len(file_proto_ransomeye_proto_rawDesc)))
	})
	return file_proto_ransomeye_proto_rawDescData
}

var file_proto_ransomeye_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_ransomeye_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_ransomeye_proto_goTypes = []any{
	(EmitterType)(0),              // 0: ransomeye.EmitterType
	(ActionType)(0),               // 1: ransomeye.ActionType
	(ActionStatus)(0),             // 2: ransomeye.ActionStatus
	(*HandshakeRequest)(nil),      // 3: ransomeye.HandshakeRequest
	(*HandshakeResponse)(nil),     // 4: ransomeye.HandshakeResponse
	(*TelemetryEnvelope)(nil),     // 5: ransomeye.TelemetryEnvelope
	(*TelemetryAck)(nil),          // 6: ransomeye.TelemetryAck
	(*SignalEnvelope)(nil),        // 7: ransomeye.SignalEnvelope
	(*SignalAck)(nil),             // 8: ransomeye.SignalAck
	(*HeartbeatRequest)(nil),      // 9: ransomeye.HeartbeatRequest
	(*HeartbeatAck)(nil),          // 10: ransomeye.HeartbeatAck
	(*ActionCommand)(nil),         // 11: ransomeye.ActionCommand
	(*ActionResult)(nil),          // 12: ransomeye.ActionResult
	(*ActionAck)(nil),             // 13: ransomeye.ActionAck
	(*FlowBatch)(nil),             // 14: ransomeye.FlowBatch
	(*Flow)(nil),                  // 15: ransomeye.Flow
	(*DPIDetectionEvent)(nil),     // 16: ransomeye.DPIDetectionEvent
	(*ActionStreamRequest)(nil),   // 17: ransomeye.ActionStreamRequest
	(*FlowAck)(nil),               // 18: ransomeye.FlowAck
	(*DPIEventAck)(nil),           // 19: ransomeye.DPIEventAck
	(*ProbeRegistration)(nil),     // 20: ransomeye.ProbeRegistration
	(*ProbeRegistrationAck)(nil),  // 21: ransomeye.ProbeRegistrationAck
	(*ProbeHeartbeatRequest)(nil), // 22: ransomeye.ProbeHeartbeatRequest
	(*ProbeHeartbeatAck)(nil),     // 23: ransomeye.ProbeHeartbeatAck
	(*PullConfigRequest)(nil),     // 24: ransomeye.PullConfigRequest
	(*ProbeConfig)(nil),           // 25: ransomeye.ProbeConfig
	(*NetworkInfraFinding)(nil),   // 26: ransomeye.NetworkInfraFinding
	(*FindingAck)(nil),            // 27: ransomeye.FindingAck
}
var file_proto_ransomeye_proto_depIdxs = []int32{
	0,  // 0: ransomeye.SignalEnvelope.emitter_type:type_name -> ransomeye.EmitterType
	1,  // 1: ransomeye.ActionCommand.action_type:type_name -> ransomeye.ActionType
	2,  // 2: ransomeye.ActionResult.status:type_name -> ransomeye.ActionStatus
	15, // 3: ransomeye.FlowBatch.flows:type_name -> ransomeye.Flow
	3,  // 4: ransomeye.RansomEyeService.Handshake:input_type -> ransomeye.HandshakeRequest
	5,  // 5: ransomeye.RansomEyeService.SendTelemetry:input_type -> ransomeye.TelemetryEnvelope
	7,  // 6: ransomeye.RansomEyeService.SendSignal:input_type -> ransomeye.SignalEnvelope
	9,  // 7: ransomeye.RansomEyeService.SendHeartbeat:input_type -> ransomeye.HeartbeatRequest
	17, // 8: ransomeye.RansomEyeService.ReceiveActions:input_type -> ransomeye.ActionStreamRequest
	12, // 9: ransomeye.RansomEyeService.ReportActionResult:input_type -> ransomeye.ActionResult
	14, // 10: ransomeye.RansomEyeService.SendFlowStream:input_type -> ransomeye.FlowBatch
	16, // 11: ransomeye.RansomEyeService.SendDPIEvent:input_type -> ransomeye.DPIDetectionEvent
	20, // 12: ransomeye.ProbeService.RegisterProbe:input_type -> ransomeye.ProbeRegistration
	22, // 13: ransomeye.ProbeService.ProbeHeartbeat:input_type -> ransomeye.ProbeHeartbeatRequest
	24, // 14: ransomeye.ProbeService.PullConfig:input_type -> ransomeye.PullConfigRequest
	26, // 15: ransomeye.ProbeService.ReportFinding:input_type -> ransomeye.NetworkInfraFinding
	4,  // 16: ransomeye.RansomEyeService.Handshake:output_type -> ransomeye.HandshakeResponse
	6,  // 17: ransomeye.RansomEyeService.SendTelemetry:output_type -> ransomeye.TelemetryAck
	8,  // 18: ransomeye.RansomEyeService.SendSignal:output_type -> ransomeye.SignalAck
	10, // 19: ransomeye.RansomEyeService.SendHeartbeat:output_type -> ransomeye.HeartbeatAck
	11, // 20: ransomeye.RansomEyeService.ReceiveActions:output_type -> ransomeye.ActionCommand
	13, // 21: ransomeye.RansomEyeService.ReportActionResult:output_type -> ransomeye.ActionAck
	18, // 22: ransomeye.RansomEyeService.SendFlowStream:output_type -> ransomeye.FlowAck
	19, // 23: ransomeye.RansomEyeService.SendDPIEvent:output_type -> ransomeye.DPIEventAck
	21, // 24: ransomeye.ProbeService.RegisterProbe:output_type -> ransomeye.ProbeRegistrationAck
	23, // 25: ransomeye.ProbeService.ProbeHeartbeat:output_type -> ransomeye.ProbeHeartbeatAck
	25, // 26: ransomeye.ProbeService.PullConfig:output_type -> ransomeye.ProbeConfig
	27, // 27: ransomeye.ProbeService.ReportFinding:output_type -> ransomeye.FindingAck
	16, // [16:28] is the sub-list for method output_type
	4,  // [4:16] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_ransomeye_proto_init() }
func file_proto_ransomeye_proto_init() {
	if File_proto_ransomeye_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ransomeye_proto_rawDesc), len(file_proto_ransomeye_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_ransomeye_proto_goTypes,
		DependencyIndexes: file_proto_ransomeye_proto_depIdxs,
		EnumInfos:         file_proto_ransomeye_proto_enumTypes,
		MessageInfos:      file_proto_ransomeye_proto_msgTypes,
	}.Build()
	File_proto_ransomeye_proto = out.File
	file_proto_ransomeye_proto_goTypes = nil
	file_proto_ransomeye_proto_depIdxs = nil
}
