// Package forensics — Merkle tree hashing per RFC 6962 (Certificate Transparency).
//
// LeafHash  = SHA256(0x00 || data)
// NodeHash  = SHA256(0x01 || left || right)
//
// MerkleTreeHash(D[0:n]) for n > 1: let k = largest power of two less than n;
// MTH(D[0:n]) = NodeHash(MTH(D[0:k]), MTH(D[k:n])).

package forensics

import (
	"crypto/sha256"
	"crypto/subtle"
	"fmt"
)

const merkleLeafPrefix = 0x00
const merkleNodePrefix = 0x01

// Proof step encoding for RFC6962 inclusion proofs.
// Each proof element is 33 bytes: [side_tag || sibling_hash32]
// side_tag: 0x00 => sibling is on the left, current is on the right.
//
//	0x01 => sibling is on the right, current is on the left.
const (
	proofSiblingLeftTag  byte = 0x00
	proofSiblingRightTag byte = 0x01
	proofStepLen              = 1 + sha256.Size
)

// LeafHash returns RFC 6962 MTH_leaf(d) = SHA256(0x00 || d).
func LeafHash(data []byte) []byte {
	h := sha256.New()
	_, _ = h.Write([]byte{merkleLeafPrefix})
	_, _ = h.Write(data)
	return h.Sum(nil)
}

// NodeHash returns RFC 6962 hash of an internal node from two child subtree hashes.
func NodeHash(left, right []byte) []byte {
	if len(left) != sha256.Size || len(right) != sha256.Size {
		panic("forensics: NodeHash children must be 32-byte hashes")
	}
	h := sha256.New()
	_, _ = h.Write([]byte{merkleNodePrefix})
	_, _ = h.Write(left)
	_, _ = h.Write(right)
	return h.Sum(nil)
}

// largestPow2LessThan returns the largest power of two strictly less than n (n > 1).
func largestPow2LessThan(n int) int {
	k := 1
	for k<<1 < n {
		k <<= 1
	}
	return k
}

// MerkleTreeHash computes RFC 6962 Merkle Tree Hash over leaf pre-images (each slice is one leaf's data).
func MerkleTreeHash(leafData [][]byte) ([]byte, error) {
	n := len(leafData)
	switch n {
	case 0:
		return nil, fmt.Errorf("forensics: MerkleTreeHash requires at least one leaf")
	case 1:
		out := LeafHash(leafData[0])
		cp := make([]byte, len(out))
		copy(cp, out)
		return cp, nil
	default:
		k := largestPow2LessThan(n)
		left, err := MerkleTreeHash(leafData[:k])
		if err != nil {
			return nil, err
		}
		right, err := MerkleTreeHash(leafData[k:])
		if err != nil {
			return nil, err
		}
		return NodeHash(left, right), nil
	}
}

func encodeProofStep(siblingHash []byte, siblingOnRight bool) ([]byte, error) {
	if len(siblingHash) != sha256.Size {
		return nil, fmt.Errorf("forensics: encodeProofStep sibling hash len=%d", len(siblingHash))
	}
	step := make([]byte, proofStepLen)
	if siblingOnRight {
		step[0] = proofSiblingRightTag
	} else {
		step[0] = proofSiblingLeftTag
	}
	copy(step[1:], siblingHash)
	return step, nil
}

// GenerateInclusionProof builds an RFC6962-compliant inclusion proof (audit path)
// for a given leaf index.
//
// proof is ordered from leaf to root (bottom-up),
// each step folds into the running hash.
func GenerateInclusionProof(leaves [][]byte, index int) [][]byte {
	if len(leaves) == 0 || index < 0 || index >= len(leaves) {
		return nil
	}
	if len(leaves) == 1 {
		return [][]byte{}
	}

	var rec func(slice [][]byte, idx int) ([][]byte, error)
	rec = func(slice [][]byte, idx int) ([][]byte, error) {
		switch len(slice) {
		case 0:
			return nil, fmt.Errorf("forensics: inclusion proof on empty slice")
		case 1:
			// No siblings at the leaf level.
			return [][]byte{}, nil
		default:
			n := len(slice)
			k := largestPow2LessThan(n)
			if idx < k {
				rightRoot, err := MerkleTreeHash(slice[k:])
				if err != nil {
					return nil, err
				}
				step, err := encodeProofStep(rightRoot, true /* sibling on right */)
				if err != nil {
					return nil, err
				}
				leftProof, err := rec(slice[:k], idx)
				if err != nil {
					return nil, err
				}
				// Return bottom-up: combine inside the left subtree first, then fold in the right sibling.
				return append(leftProof, step), nil
			}

			leftRoot, err := MerkleTreeHash(slice[:k])
			if err != nil {
				return nil, err
			}
			step, err := encodeProofStep(leftRoot, false /* sibling on left */)
			if err != nil {
				return nil, err
			}
			rightProof, err := rec(slice[k:], idx-k)
			if err != nil {
				return nil, err
			}
			// Return bottom-up: combine inside the right subtree first, then fold in the left sibling.
			return append(rightProof, step), nil
		}
	}

	proof, err := rec(leaves, index)
	if err != nil {
		return nil
	}
	return proof
}

// VerifyInclusionProof verifies an RFC6962 inclusion proof.
//
// proof must be the tagged sibling list generated by GenerateInclusionProof.
// root must be the RFC6962 Merkle tree hash of all leaves (MTH).
func VerifyInclusionProof(leaf []byte, proof [][]byte, root []byte, index int) bool {
	_ = index // index is not needed because proof elements preserve left/right positioning.

	if len(root) != sha256.Size {
		return false
	}
	if len(proof) == 0 {
		// n=1 trees produce empty audit paths.
		h := LeafHash(leaf)
		return subtle.ConstantTimeCompare(h, root) == 1
	}

	cur := LeafHash(leaf)
	for _, step := range proof {
		if len(step) != proofStepLen {
			return false
		}
		tag := step[0]
		sibling := step[1:]
		if len(sibling) != sha256.Size {
			return false
		}

		switch tag {
		case proofSiblingLeftTag:
			// sibling on left, current on right => NodeHash(sibling, cur)
			cur = NodeHash(sibling, cur)
		case proofSiblingRightTag:
			// current on left, sibling on right => NodeHash(cur, sibling)
			cur = NodeHash(cur, sibling)
		default:
			return false
		}
	}

	return subtle.ConstantTimeCompare(cur, root) == 1
}
