// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/dpi_event.proto

package dpieventpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Canonical signed DPI sensor output for trusted UNIX-socket ingress.
type DpiEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Seq              uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	FlowHash         uint64                 `protobuf:"varint,2,opt,name=flow_hash,json=flowHash,proto3" json:"flow_hash,omitempty"`
	ClassificationId uint32                 `protobuf:"varint,3,opt,name=classification_id,json=classificationId,proto3" json:"classification_id,omitempty"`
	ConfidenceFp     uint32                 `protobuf:"varint,4,opt,name=confidence_fp,json=confidenceFp,proto3" json:"confidence_fp,omitempty"`
	PayloadHash      []byte                 `protobuf:"bytes,5,opt,name=payload_hash,json=payloadHash,proto3" json:"payload_hash,omitempty"` // SHA-256 only; raw packet payload is forbidden.
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DpiEvent) Reset() {
	*x = DpiEvent{}
	mi := &file_proto_dpi_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DpiEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DpiEvent) ProtoMessage() {}

func (x *DpiEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dpi_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DpiEvent.ProtoReflect.Descriptor instead.
func (*DpiEvent) Descriptor() ([]byte, []int) {
	return file_proto_dpi_event_proto_rawDescGZIP(), []int{0}
}

func (x *DpiEvent) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *DpiEvent) GetFlowHash() uint64 {
	if x != nil {
		return x.FlowHash
	}
	return 0
}

func (x *DpiEvent) GetClassificationId() uint32 {
	if x != nil {
		return x.ClassificationId
	}
	return 0
}

func (x *DpiEvent) GetConfidenceFp() uint32 {
	if x != nil {
		return x.ConfidenceFp
	}
	return 0
}

func (x *DpiEvent) GetPayloadHash() []byte {
	if x != nil {
		return x.PayloadHash
	}
	return nil
}

type DpiEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	DroppedBefore uint64                 `protobuf:"varint,3,opt,name=dropped_before,json=droppedBefore,proto3" json:"dropped_before,omitempty"` // Packets dropped in probe before this event.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DpiEnvelope) Reset() {
	*x = DpiEnvelope{}
	mi := &file_proto_dpi_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DpiEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DpiEnvelope) ProtoMessage() {}

func (x *DpiEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dpi_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DpiEnvelope.ProtoReflect.Descriptor instead.
func (*DpiEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_dpi_event_proto_rawDescGZIP(), []int{1}
}

func (x *DpiEnvelope) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *DpiEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DpiEnvelope) GetDroppedBefore() uint64 {
	if x != nil {
		return x.DroppedBefore
	}
	return 0
}

var File_proto_dpi_event_proto protoreflect.FileDescriptor

const file_proto_dpi_event_proto_rawDesc = "" +
	"\n" +
	"\x15proto/dpi_event.proto\x12\rransomeye.dpi\"\xae\x01\n" +
	"\bDpiEvent\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x1b\n" +
	"\tflow_hash\x18\x02 \x01(\x04R\bflowHash\x12+\n" +
	"\x11classification_id\x18\x03 \x01(\rR\x10classificationId\x12#\n" +
	"\rconfidence_fp\x18\x04 \x01(\rR\fconfidenceFp\x12!\n" +
	"\fpayload_hash\x18\x05 \x01(\fR\vpayloadHash\"`\n" +
	"\vDpiEnvelope\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12%\n" +
	"\x0edropped_before\x18\x03 \x01(\x04R\rdroppedBeforeB'Z%ransomeye/proto/dpieventpb;dpieventpbb\x06proto3"

var (
	file_proto_dpi_event_proto_rawDescOnce sync.Once
	file_proto_dpi_event_proto_rawDescData []byte
)

func file_proto_dpi_event_proto_rawDescGZIP() []byte {
	file_proto_dpi_event_proto_rawDescOnce.Do(func() {
		file_proto_dpi_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dpi_event_proto_rawDesc), len(file_proto_dpi_event_proto_rawDesc)))
	})
	return file_proto_dpi_event_proto_rawDescData
}

var file_proto_dpi_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_dpi_event_proto_goTypes = []any{
	(*DpiEvent)(nil),    // 0: ransomeye.dpi.DpiEvent
	(*DpiEnvelope)(nil), // 1: ransomeye.dpi.DpiEnvelope
}
var file_proto_dpi_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_dpi_event_proto_init() }
func file_proto_dpi_event_proto_init() {
	if File_proto_dpi_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dpi_event_proto_rawDesc), len(file_proto_dpi_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_dpi_event_proto_goTypes,
		DependencyIndexes: file_proto_dpi_event_proto_depIdxs,
		MessageInfos:      file_proto_dpi_event_proto_msgTypes,
	}.Build()
	File_proto_dpi_event_proto = out.File
	file_proto_dpi_event_proto_goTypes = nil
	file_proto_dpi_event_proto_depIdxs = nil
}
