// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/internal_ai.proto

package internalaipb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIDetectionService_EvaluateTelemetry_FullMethodName = "/ransomeye.internalai.AIDetectionService/EvaluateTelemetry"
)

// AIDetectionServiceClient is the client API for AIDetectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIDetectionServiceClient interface {
	EvaluateTelemetry(ctx context.Context, in *EvaluationRequest, opts ...grpc.CallOption) (*EvaluationResponse, error)
}

type aIDetectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIDetectionServiceClient(cc grpc.ClientConnInterface) AIDetectionServiceClient {
	return &aIDetectionServiceClient{cc}
}

func (c *aIDetectionServiceClient) EvaluateTelemetry(ctx context.Context, in *EvaluationRequest, opts ...grpc.CallOption) (*EvaluationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluationResponse)
	err := c.cc.Invoke(ctx, AIDetectionService_EvaluateTelemetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIDetectionServiceServer is the server API for AIDetectionService service.
// All implementations must embed UnimplementedAIDetectionServiceServer
// for forward compatibility.
type AIDetectionServiceServer interface {
	EvaluateTelemetry(context.Context, *EvaluationRequest) (*EvaluationResponse, error)
	mustEmbedUnimplementedAIDetectionServiceServer()
}

// UnimplementedAIDetectionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIDetectionServiceServer struct{}

func (UnimplementedAIDetectionServiceServer) EvaluateTelemetry(context.Context, *EvaluationRequest) (*EvaluationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluateTelemetry not implemented")
}
func (UnimplementedAIDetectionServiceServer) mustEmbedUnimplementedAIDetectionServiceServer() {}
func (UnimplementedAIDetectionServiceServer) testEmbeddedByValue()                            {}

// UnsafeAIDetectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIDetectionServiceServer will
// result in compilation errors.
type UnsafeAIDetectionServiceServer interface {
	mustEmbedUnimplementedAIDetectionServiceServer()
}

func RegisterAIDetectionServiceServer(s grpc.ServiceRegistrar, srv AIDetectionServiceServer) {
	// If the following call pancis, it indicates UnimplementedAIDetectionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIDetectionService_ServiceDesc, srv)
}

func _AIDetectionService_EvaluateTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIDetectionServiceServer).EvaluateTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIDetectionService_EvaluateTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIDetectionServiceServer).EvaluateTelemetry(ctx, req.(*EvaluationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIDetectionService_ServiceDesc is the grpc.ServiceDesc for AIDetectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIDetectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ransomeye.internalai.AIDetectionService",
	HandlerType: (*AIDetectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvaluateTelemetry",
			Handler:    _AIDetectionService_EvaluateTelemetry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/internal_ai.proto",
}

const (
	IntelService_GetIntelIndicator_FullMethodName = "/ransomeye.internalai.IntelService/GetIntelIndicator"
)

// IntelServiceClient is the client API for IntelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IntelServiceClient interface {
	GetIntelIndicator(ctx context.Context, in *IntelRequest, opts ...grpc.CallOption) (*IntelResponse, error)
}

type intelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIntelServiceClient(cc grpc.ClientConnInterface) IntelServiceClient {
	return &intelServiceClient{cc}
}

func (c *intelServiceClient) GetIntelIndicator(ctx context.Context, in *IntelRequest, opts ...grpc.CallOption) (*IntelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntelResponse)
	err := c.cc.Invoke(ctx, IntelService_GetIntelIndicator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntelServiceServer is the server API for IntelService service.
// All implementations must embed UnimplementedIntelServiceServer
// for forward compatibility.
type IntelServiceServer interface {
	GetIntelIndicator(context.Context, *IntelRequest) (*IntelResponse, error)
	mustEmbedUnimplementedIntelServiceServer()
}

// UnimplementedIntelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIntelServiceServer struct{}

func (UnimplementedIntelServiceServer) GetIntelIndicator(context.Context, *IntelRequest) (*IntelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIntelIndicator not implemented")
}
func (UnimplementedIntelServiceServer) mustEmbedUnimplementedIntelServiceServer() {}
func (UnimplementedIntelServiceServer) testEmbeddedByValue()                      {}

// UnsafeIntelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntelServiceServer will
// result in compilation errors.
type UnsafeIntelServiceServer interface {
	mustEmbedUnimplementedIntelServiceServer()
}

func RegisterIntelServiceServer(s grpc.ServiceRegistrar, srv IntelServiceServer) {
	// If the following call pancis, it indicates UnimplementedIntelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IntelService_ServiceDesc, srv)
}

func _IntelService_GetIntelIndicator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelServiceServer).GetIntelIndicator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntelService_GetIntelIndicator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelServiceServer).GetIntelIndicator(ctx, req.(*IntelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IntelService_ServiceDesc is the grpc.ServiceDesc for IntelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IntelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ransomeye.internalai.IntelService",
	HandlerType: (*IntelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIntelIndicator",
			Handler:    _IntelService_GetIntelIndicator_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/internal_ai.proto",
}
